branch-defaults:
  master:
    environment: flask-env
    group_suffix: null
global:
  application_name: flask-auth-server
  branch: null
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: us-west-2
  profile: null
  repository: null
  sc: git
